{% set name = "trollius" %}
{% set version = "2.2.post1" %}
{% set sha256 = "1667f915b1fe11d237bb1ea380a8920d11b4ee7c5744220bdd656076cd24441b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py>35]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - python
    - setuptools

  run:
    - python
    - six
    - futures  # [py27]

test:
  imports:
    - trollius
    - trollius._overlapped  # [win]

about:
  home: https://github.com/haypo/trollius
  license: Apache-2.0
  license_family: Apache 
  license_file: COPYING
  summary: 'Port of the Tulip project (asyncio module, PEP 3156) on Python 2'

  description: |
    Trollius provides infrastructure for writing single-threaded
    concurrent code using coroutines, multiplexing I/O access over
    sockets and other resources, running network clients and servers,
    and other related primitives.
  doc_url: http://trollius.readthedocs.io
  doc_source_url: https://github.com/haypo/trollius/blob/trollius/doc/index.rst
  dev_url: https://github.com/haypo/trollius

extra:
  recipe-maintainers:
    - curtisalexander
