travis:
  secure:
    BINSTAR_TOKEN: VFaUSZUf2FSkTs1dAQwo8tbs+fUH/5wWS+Qfrs35wGsRN+51b4nv5O0oUOrjEu3jE4W45mWirEJt6/I7bjZoFhVcWuRyzVMu9SGfv559uC8SDNfIvhj6WXQrMiU5G8d7tB+KHwfasFK7s7jFg+Bxl5Lp0NMQPtE1xpOf5sCsylycutYPrJIkvQ3KScT9yIIdHFs5IfvFNcs5TdGxybvmhN4QKsdApz3A7Es4WRZLNphnMuot+l7N5+163wOAPEu8KRhRxOb6jLb5aCXZGWDyym83vWowbyGNWwIOW0tj542JeumyYaOSls69OpoqOw2Wrjon2a5ULgRxrBrMj4O485EhB4dVV9IzxNEiAbaZhnN2OlT37DKHbFTmCGOVbGUToNM7lkkUfTE3pwVF69aNefBDxZKzJHHY/Go4nzWJfqo5TpuSkPkyqQnyqbQf9sI6tm+VaK4L/Gh8ctgxwyNQNQqK0S1uAHwCfa/a7m5q9VRbBC+K1QUbVbHIyr/rWTg8YmCOWaPuo3ZNyh1RdqhIMYJKhDjI1fyuNQ+Zi9sVtXUFBShUSEqzg3Z/oYkvwBs6lpFsGYSwMjsv84kRx9+axrGOyKT/hOLuuhqLOjoGLswazIEpXvOe+Xeri1zfAZYaBvNgh0SobXyzLG80gx32ApsKH0xRK4+T1nti1UodF+I=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
