travis:
  secure:
    BINSTAR_TOKEN: MOvcNQsHkIr9PPAhP+UypSajwOAvxGSJCmpVHm4nSr8s26FlQxPOJyRZpEVuOyVWbcRL3MTV/xSQ94Mhhn/x2h13oY0XFD7ebaExZKSvNRqaAtBCe1soE33USbSGdaaYtoZwV9b1bKEfrn/G4Hc5AVtQ9pncpUcy6+CDdCnKapE/Wkt+nK1w4+lG6rRGH9nLc9XyTlbfvqpvJuT3KVndY9OIh/RLMe73twGz1gNCjAnkqDXDqHt5yIy1f585qBFK5XTaQzKRsMgZmvhTaGaMMWrwhwYpcH/HDiiuWTt1XBdaVZeg/nJbpXD+K9P9jOVQb/pTiQoHq9RZJ5uve3y7j4iXqdgIMAX9pmUnvJ/Yo4srltvFYcbXNgDT3I4NeG47iijBLz0C42K9LwBLuohPALlyBluDK1Ugqu4FOpVWQ1AOXMKh8g2QaOGYvnARMxMlnOur0IlLAgPD+zFgvh+1FFnvzhX9CbLZedAHYu3MTXPVg0MOmkGlkzyhRlAQbA6DJWsWlEz9I/IZ1FlkCkxixLYAbX/eK2CTXG8GASBczL6cAlRWVT4djGE1UKcSwIXtiN5znVCOgic/VWc5hu/2Tg+PZdYOG+Vp5f5FgeWFjPi+dVFjV0al6A4TGgFkYZ+zpK6oR/fHsGNgpXG5NYToPcRNn+gMVCmOGMFRhu4Uyow=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
